pub(crate) fn from_winit_modifiers(
    value: winit::keyboard::ModifiersState,
) -> Option<clew::keyboard::KeyModifiers> {
    clew::keyboard::KeyModifiers::from_bits(value.bits())
}

pub(crate) fn from_winit_key_code(
    value: winit::keyboard::KeyCode,
) -> Option<clew::keyboard::KeyCode> {
    match value {
        winit::keyboard::KeyCode::Backquote => Some(clew::keyboard::KeyCode::Backquote),
        winit::keyboard::KeyCode::Backslash => Some(clew::keyboard::KeyCode::Backslash),
        winit::keyboard::KeyCode::BracketLeft => Some(clew::keyboard::KeyCode::BracketLeft),
        winit::keyboard::KeyCode::BracketRight => Some(clew::keyboard::KeyCode::BracketRight),
        winit::keyboard::KeyCode::Comma => Some(clew::keyboard::KeyCode::Comma),
        winit::keyboard::KeyCode::Digit0 => Some(clew::keyboard::KeyCode::Digit0),
        winit::keyboard::KeyCode::Digit1 => Some(clew::keyboard::KeyCode::Digit1),
        winit::keyboard::KeyCode::Digit2 => Some(clew::keyboard::KeyCode::Digit2),
        winit::keyboard::KeyCode::Digit3 => Some(clew::keyboard::KeyCode::Digit3),
        winit::keyboard::KeyCode::Digit4 => Some(clew::keyboard::KeyCode::Digit4),
        winit::keyboard::KeyCode::Digit5 => Some(clew::keyboard::KeyCode::Digit5),
        winit::keyboard::KeyCode::Digit6 => Some(clew::keyboard::KeyCode::Digit6),
        winit::keyboard::KeyCode::Digit7 => Some(clew::keyboard::KeyCode::Digit7),
        winit::keyboard::KeyCode::Digit8 => Some(clew::keyboard::KeyCode::Digit8),
        winit::keyboard::KeyCode::Digit9 => Some(clew::keyboard::KeyCode::Digit9),
        winit::keyboard::KeyCode::Equal => Some(clew::keyboard::KeyCode::Equal),
        winit::keyboard::KeyCode::IntlBackslash => Some(clew::keyboard::KeyCode::IntlBackslash),
        winit::keyboard::KeyCode::IntlRo => Some(clew::keyboard::KeyCode::IntlRo),
        winit::keyboard::KeyCode::IntlYen => Some(clew::keyboard::KeyCode::IntlYen),
        winit::keyboard::KeyCode::KeyA => Some(clew::keyboard::KeyCode::KeyA),
        winit::keyboard::KeyCode::KeyB => Some(clew::keyboard::KeyCode::KeyB),
        winit::keyboard::KeyCode::KeyC => Some(clew::keyboard::KeyCode::KeyC),
        winit::keyboard::KeyCode::KeyD => Some(clew::keyboard::KeyCode::KeyD),
        winit::keyboard::KeyCode::KeyE => Some(clew::keyboard::KeyCode::KeyE),
        winit::keyboard::KeyCode::KeyF => Some(clew::keyboard::KeyCode::KeyF),
        winit::keyboard::KeyCode::KeyG => Some(clew::keyboard::KeyCode::KeyG),
        winit::keyboard::KeyCode::KeyH => Some(clew::keyboard::KeyCode::KeyH),
        winit::keyboard::KeyCode::KeyI => Some(clew::keyboard::KeyCode::KeyI),
        winit::keyboard::KeyCode::KeyJ => Some(clew::keyboard::KeyCode::KeyJ),
        winit::keyboard::KeyCode::KeyK => Some(clew::keyboard::KeyCode::KeyK),
        winit::keyboard::KeyCode::KeyL => Some(clew::keyboard::KeyCode::KeyL),
        winit::keyboard::KeyCode::KeyM => Some(clew::keyboard::KeyCode::KeyM),
        winit::keyboard::KeyCode::KeyN => Some(clew::keyboard::KeyCode::KeyN),
        winit::keyboard::KeyCode::KeyO => Some(clew::keyboard::KeyCode::KeyO),
        winit::keyboard::KeyCode::KeyP => Some(clew::keyboard::KeyCode::KeyP),
        winit::keyboard::KeyCode::KeyQ => Some(clew::keyboard::KeyCode::KeyQ),
        winit::keyboard::KeyCode::KeyR => Some(clew::keyboard::KeyCode::KeyR),
        winit::keyboard::KeyCode::KeyS => Some(clew::keyboard::KeyCode::KeyS),
        winit::keyboard::KeyCode::KeyT => Some(clew::keyboard::KeyCode::KeyT),
        winit::keyboard::KeyCode::KeyU => Some(clew::keyboard::KeyCode::KeyU),
        winit::keyboard::KeyCode::KeyV => Some(clew::keyboard::KeyCode::KeyV),
        winit::keyboard::KeyCode::KeyW => Some(clew::keyboard::KeyCode::KeyW),
        winit::keyboard::KeyCode::KeyX => Some(clew::keyboard::KeyCode::KeyX),
        winit::keyboard::KeyCode::KeyY => Some(clew::keyboard::KeyCode::KeyY),
        winit::keyboard::KeyCode::KeyZ => Some(clew::keyboard::KeyCode::KeyZ),
        winit::keyboard::KeyCode::Minus => Some(clew::keyboard::KeyCode::Minus),
        winit::keyboard::KeyCode::Period => Some(clew::keyboard::KeyCode::Period),
        winit::keyboard::KeyCode::Quote => Some(clew::keyboard::KeyCode::Quote),
        winit::keyboard::KeyCode::Semicolon => Some(clew::keyboard::KeyCode::Semicolon),
        winit::keyboard::KeyCode::Slash => Some(clew::keyboard::KeyCode::Slash),
        winit::keyboard::KeyCode::AltLeft => Some(clew::keyboard::KeyCode::AltLeft),
        winit::keyboard::KeyCode::AltRight => Some(clew::keyboard::KeyCode::AltRight),
        winit::keyboard::KeyCode::Backspace => Some(clew::keyboard::KeyCode::Backspace),
        winit::keyboard::KeyCode::CapsLock => Some(clew::keyboard::KeyCode::CapsLock),
        winit::keyboard::KeyCode::ContextMenu => Some(clew::keyboard::KeyCode::ContextMenu),
        winit::keyboard::KeyCode::ControlLeft => Some(clew::keyboard::KeyCode::ControlLeft),
        winit::keyboard::KeyCode::ControlRight => Some(clew::keyboard::KeyCode::ControlRight),
        winit::keyboard::KeyCode::Enter => Some(clew::keyboard::KeyCode::Enter),
        winit::keyboard::KeyCode::SuperLeft => Some(clew::keyboard::KeyCode::SuperLeft),
        winit::keyboard::KeyCode::SuperRight => Some(clew::keyboard::KeyCode::SuperRight),
        winit::keyboard::KeyCode::ShiftLeft => Some(clew::keyboard::KeyCode::ShiftLeft),
        winit::keyboard::KeyCode::ShiftRight => Some(clew::keyboard::KeyCode::ShiftRight),
        winit::keyboard::KeyCode::Space => Some(clew::keyboard::KeyCode::Space),
        winit::keyboard::KeyCode::Tab => Some(clew::keyboard::KeyCode::Tab),
        winit::keyboard::KeyCode::Convert => Some(clew::keyboard::KeyCode::Convert),
        winit::keyboard::KeyCode::KanaMode => Some(clew::keyboard::KeyCode::KanaMode),
        winit::keyboard::KeyCode::Lang1 => Some(clew::keyboard::KeyCode::Lang1),
        winit::keyboard::KeyCode::Lang2 => Some(clew::keyboard::KeyCode::Lang2),
        winit::keyboard::KeyCode::Lang3 => Some(clew::keyboard::KeyCode::Lang3),
        winit::keyboard::KeyCode::Lang4 => Some(clew::keyboard::KeyCode::Lang4),
        winit::keyboard::KeyCode::Lang5 => Some(clew::keyboard::KeyCode::Lang5),
        winit::keyboard::KeyCode::NonConvert => Some(clew::keyboard::KeyCode::NonConvert),
        winit::keyboard::KeyCode::Delete => Some(clew::keyboard::KeyCode::Delete),
        winit::keyboard::KeyCode::End => Some(clew::keyboard::KeyCode::End),
        winit::keyboard::KeyCode::Help => Some(clew::keyboard::KeyCode::Help),
        winit::keyboard::KeyCode::Home => Some(clew::keyboard::KeyCode::Home),
        winit::keyboard::KeyCode::Insert => Some(clew::keyboard::KeyCode::Insert),
        winit::keyboard::KeyCode::PageDown => Some(clew::keyboard::KeyCode::PageDown),
        winit::keyboard::KeyCode::PageUp => Some(clew::keyboard::KeyCode::PageUp),
        winit::keyboard::KeyCode::ArrowDown => Some(clew::keyboard::KeyCode::ArrowDown),
        winit::keyboard::KeyCode::ArrowLeft => Some(clew::keyboard::KeyCode::ArrowLeft),
        winit::keyboard::KeyCode::ArrowRight => Some(clew::keyboard::KeyCode::ArrowRight),
        winit::keyboard::KeyCode::ArrowUp => Some(clew::keyboard::KeyCode::ArrowUp),
        winit::keyboard::KeyCode::NumLock => Some(clew::keyboard::KeyCode::NumLock),
        winit::keyboard::KeyCode::Numpad0 => Some(clew::keyboard::KeyCode::Numpad0),
        winit::keyboard::KeyCode::Numpad1 => Some(clew::keyboard::KeyCode::Numpad1),
        winit::keyboard::KeyCode::Numpad2 => Some(clew::keyboard::KeyCode::Numpad2),
        winit::keyboard::KeyCode::Numpad3 => Some(clew::keyboard::KeyCode::Numpad3),
        winit::keyboard::KeyCode::Numpad4 => Some(clew::keyboard::KeyCode::Numpad4),
        winit::keyboard::KeyCode::Numpad5 => Some(clew::keyboard::KeyCode::Numpad5),
        winit::keyboard::KeyCode::Numpad6 => Some(clew::keyboard::KeyCode::Numpad6),
        winit::keyboard::KeyCode::Numpad7 => Some(clew::keyboard::KeyCode::Numpad7),
        winit::keyboard::KeyCode::Numpad8 => Some(clew::keyboard::KeyCode::Numpad8),
        winit::keyboard::KeyCode::Numpad9 => Some(clew::keyboard::KeyCode::Numpad9),
        winit::keyboard::KeyCode::NumpadAdd => Some(clew::keyboard::KeyCode::NumpadAdd),
        winit::keyboard::KeyCode::NumpadBackspace => Some(clew::keyboard::KeyCode::NumpadBackspace),
        winit::keyboard::KeyCode::NumpadClear => Some(clew::keyboard::KeyCode::NumpadClear),
        winit::keyboard::KeyCode::NumpadClearEntry => {
            Some(clew::keyboard::KeyCode::NumpadClearEntry)
        }
        winit::keyboard::KeyCode::NumpadComma => Some(clew::keyboard::KeyCode::NumpadComma),
        winit::keyboard::KeyCode::NumpadDecimal => Some(clew::keyboard::KeyCode::NumpadDecimal),
        winit::keyboard::KeyCode::NumpadDivide => Some(clew::keyboard::KeyCode::NumpadDivide),
        winit::keyboard::KeyCode::NumpadEnter => Some(clew::keyboard::KeyCode::NumpadEnter),
        winit::keyboard::KeyCode::NumpadEqual => Some(clew::keyboard::KeyCode::NumpadEqual),
        winit::keyboard::KeyCode::NumpadHash => Some(clew::keyboard::KeyCode::NumpadHash),
        winit::keyboard::KeyCode::NumpadMemoryAdd => Some(clew::keyboard::KeyCode::NumpadMemoryAdd),
        winit::keyboard::KeyCode::NumpadMemoryClear => {
            Some(clew::keyboard::KeyCode::NumpadMemoryClear)
        }
        winit::keyboard::KeyCode::NumpadMemoryRecall => {
            Some(clew::keyboard::KeyCode::NumpadMemoryRecall)
        }
        winit::keyboard::KeyCode::NumpadMemoryStore => {
            Some(clew::keyboard::KeyCode::NumpadMemoryStore)
        }
        winit::keyboard::KeyCode::NumpadMemorySubtract => {
            Some(clew::keyboard::KeyCode::NumpadMemorySubtract)
        }
        winit::keyboard::KeyCode::NumpadMultiply => Some(clew::keyboard::KeyCode::NumpadMultiply),
        winit::keyboard::KeyCode::NumpadParenLeft => Some(clew::keyboard::KeyCode::NumpadParenLeft),
        winit::keyboard::KeyCode::NumpadParenRight => {
            Some(clew::keyboard::KeyCode::NumpadParenRight)
        }
        winit::keyboard::KeyCode::NumpadStar => Some(clew::keyboard::KeyCode::NumpadStar),
        winit::keyboard::KeyCode::NumpadSubtract => Some(clew::keyboard::KeyCode::NumpadSubtract),
        winit::keyboard::KeyCode::Escape => Some(clew::keyboard::KeyCode::Escape),
        winit::keyboard::KeyCode::Fn => Some(clew::keyboard::KeyCode::Fn),
        winit::keyboard::KeyCode::FnLock => Some(clew::keyboard::KeyCode::FnLock),
        winit::keyboard::KeyCode::PrintScreen => Some(clew::keyboard::KeyCode::PrintScreen),
        winit::keyboard::KeyCode::ScrollLock => Some(clew::keyboard::KeyCode::ScrollLock),
        winit::keyboard::KeyCode::Pause => Some(clew::keyboard::KeyCode::Pause),
        winit::keyboard::KeyCode::BrowserBack => Some(clew::keyboard::KeyCode::BrowserBack),
        winit::keyboard::KeyCode::BrowserFavorites => {
            Some(clew::keyboard::KeyCode::BrowserFavorites)
        }
        winit::keyboard::KeyCode::BrowserForward => Some(clew::keyboard::KeyCode::BrowserForward),
        winit::keyboard::KeyCode::BrowserHome => Some(clew::keyboard::KeyCode::BrowserHome),
        winit::keyboard::KeyCode::BrowserRefresh => Some(clew::keyboard::KeyCode::BrowserRefresh),
        winit::keyboard::KeyCode::BrowserSearch => Some(clew::keyboard::KeyCode::BrowserSearch),
        winit::keyboard::KeyCode::BrowserStop => Some(clew::keyboard::KeyCode::BrowserStop),
        winit::keyboard::KeyCode::Eject => Some(clew::keyboard::KeyCode::Eject),
        winit::keyboard::KeyCode::LaunchApp1 => Some(clew::keyboard::KeyCode::LaunchApp1),
        winit::keyboard::KeyCode::LaunchApp2 => Some(clew::keyboard::KeyCode::LaunchApp2),
        winit::keyboard::KeyCode::LaunchMail => Some(clew::keyboard::KeyCode::LaunchMail),
        winit::keyboard::KeyCode::MediaPlayPause => Some(clew::keyboard::KeyCode::MediaPlayPause),
        winit::keyboard::KeyCode::MediaSelect => Some(clew::keyboard::KeyCode::MediaSelect),
        winit::keyboard::KeyCode::MediaStop => Some(clew::keyboard::KeyCode::MediaStop),
        winit::keyboard::KeyCode::MediaTrackNext => Some(clew::keyboard::KeyCode::MediaTrackNext),
        winit::keyboard::KeyCode::MediaTrackPrevious => {
            Some(clew::keyboard::KeyCode::MediaTrackPrevious)
        }
        winit::keyboard::KeyCode::Power => Some(clew::keyboard::KeyCode::Power),
        winit::keyboard::KeyCode::Sleep => Some(clew::keyboard::KeyCode::Sleep),
        winit::keyboard::KeyCode::AudioVolumeDown => Some(clew::keyboard::KeyCode::AudioVolumeDown),
        winit::keyboard::KeyCode::AudioVolumeMute => Some(clew::keyboard::KeyCode::AudioVolumeMute),
        winit::keyboard::KeyCode::AudioVolumeUp => Some(clew::keyboard::KeyCode::AudioVolumeUp),
        winit::keyboard::KeyCode::WakeUp => Some(clew::keyboard::KeyCode::WakeUp),
        winit::keyboard::KeyCode::Meta => Some(clew::keyboard::KeyCode::Meta),
        winit::keyboard::KeyCode::Hyper => Some(clew::keyboard::KeyCode::Hyper),
        winit::keyboard::KeyCode::Turbo => Some(clew::keyboard::KeyCode::Turbo),
        winit::keyboard::KeyCode::Abort => Some(clew::keyboard::KeyCode::Abort),
        winit::keyboard::KeyCode::Resume => Some(clew::keyboard::KeyCode::Resume),
        winit::keyboard::KeyCode::Suspend => Some(clew::keyboard::KeyCode::Suspend),
        winit::keyboard::KeyCode::Again => Some(clew::keyboard::KeyCode::Again),
        winit::keyboard::KeyCode::Copy => Some(clew::keyboard::KeyCode::Copy),
        winit::keyboard::KeyCode::Cut => Some(clew::keyboard::KeyCode::Cut),
        winit::keyboard::KeyCode::Find => Some(clew::keyboard::KeyCode::Find),
        winit::keyboard::KeyCode::Open => Some(clew::keyboard::KeyCode::Open),
        winit::keyboard::KeyCode::Paste => Some(clew::keyboard::KeyCode::Paste),
        winit::keyboard::KeyCode::Props => Some(clew::keyboard::KeyCode::Props),
        winit::keyboard::KeyCode::Select => Some(clew::keyboard::KeyCode::Select),
        winit::keyboard::KeyCode::Undo => Some(clew::keyboard::KeyCode::Undo),
        winit::keyboard::KeyCode::Hiragana => Some(clew::keyboard::KeyCode::Hiragana),
        winit::keyboard::KeyCode::Katakana => Some(clew::keyboard::KeyCode::Katakana),
        winit::keyboard::KeyCode::F1 => Some(clew::keyboard::KeyCode::F1),
        winit::keyboard::KeyCode::F2 => Some(clew::keyboard::KeyCode::F2),
        winit::keyboard::KeyCode::F3 => Some(clew::keyboard::KeyCode::F3),
        winit::keyboard::KeyCode::F4 => Some(clew::keyboard::KeyCode::F4),
        winit::keyboard::KeyCode::F5 => Some(clew::keyboard::KeyCode::F5),
        winit::keyboard::KeyCode::F6 => Some(clew::keyboard::KeyCode::F6),
        winit::keyboard::KeyCode::F7 => Some(clew::keyboard::KeyCode::F7),
        winit::keyboard::KeyCode::F8 => Some(clew::keyboard::KeyCode::F8),
        winit::keyboard::KeyCode::F9 => Some(clew::keyboard::KeyCode::F9),
        winit::keyboard::KeyCode::F10 => Some(clew::keyboard::KeyCode::F10),
        winit::keyboard::KeyCode::F11 => Some(clew::keyboard::KeyCode::F11),
        winit::keyboard::KeyCode::F12 => Some(clew::keyboard::KeyCode::F12),
        winit::keyboard::KeyCode::F13 => Some(clew::keyboard::KeyCode::F13),
        winit::keyboard::KeyCode::F14 => Some(clew::keyboard::KeyCode::F14),
        winit::keyboard::KeyCode::F15 => Some(clew::keyboard::KeyCode::F15),
        winit::keyboard::KeyCode::F16 => Some(clew::keyboard::KeyCode::F16),
        winit::keyboard::KeyCode::F17 => Some(clew::keyboard::KeyCode::F17),
        winit::keyboard::KeyCode::F18 => Some(clew::keyboard::KeyCode::F18),
        winit::keyboard::KeyCode::F19 => Some(clew::keyboard::KeyCode::F19),
        winit::keyboard::KeyCode::F20 => Some(clew::keyboard::KeyCode::F20),
        winit::keyboard::KeyCode::F21 => Some(clew::keyboard::KeyCode::F21),
        winit::keyboard::KeyCode::F22 => Some(clew::keyboard::KeyCode::F22),
        winit::keyboard::KeyCode::F23 => Some(clew::keyboard::KeyCode::F23),
        winit::keyboard::KeyCode::F24 => Some(clew::keyboard::KeyCode::F24),
        winit::keyboard::KeyCode::F25 => Some(clew::keyboard::KeyCode::F25),
        winit::keyboard::KeyCode::F26 => Some(clew::keyboard::KeyCode::F26),
        winit::keyboard::KeyCode::F27 => Some(clew::keyboard::KeyCode::F27),
        winit::keyboard::KeyCode::F28 => Some(clew::keyboard::KeyCode::F28),
        winit::keyboard::KeyCode::F29 => Some(clew::keyboard::KeyCode::F29),
        winit::keyboard::KeyCode::F30 => Some(clew::keyboard::KeyCode::F30),
        winit::keyboard::KeyCode::F31 => Some(clew::keyboard::KeyCode::F31),
        winit::keyboard::KeyCode::F32 => Some(clew::keyboard::KeyCode::F32),
        winit::keyboard::KeyCode::F33 => Some(clew::keyboard::KeyCode::F33),
        winit::keyboard::KeyCode::F34 => Some(clew::keyboard::KeyCode::F34),
        winit::keyboard::KeyCode::F35 => Some(clew::keyboard::KeyCode::F35),
        _ => None,
    }
}
